version: "3.8"

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
