server:
  servlet:
    context-path: /rfq-service/
  shutdown: graceful
  max-http-request-header-size: 10KB
  port: 8081

springdoc:
  swagger-ui:
    path: /internal_api/
  api-docs:
    path: /internal_api/api-docs
  show-login-endpoint: true

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_DATABASE_HOST:localhost}:${POSTGRESQL_DATABASE_PORT:5432}/rfq_service
    username: ${POSTGRESQL_DATABASE_USER:postgres}
    password: ${POSTGRESQL_DATABASE_PASSWORD:postgres}
    hikari:
      data-source-properties: stringtype=unspecified

logging:
  level:
    org.springframework.web: DEBUG

app:
  api:
    supplier-facts-api:
      url: http://localhost:8080/supplier-facts-service/internal_api
    recommendation-service-api:
      url: http://localhost:8000/recommendation-service/internal_api


management:
  endpoint:
    info:
      access: read_only
    health:
      show-details: always
    metrics:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /status/
